#! /bin/sh

### BEGIN INIT INFO
# Provides:          sh-web-dashboard
# Required-Start:    $remote_fs $syslog mosquitto
# Required-Stop:     $remote_fs $syslog mosquitto
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start sh-web-dashboard at boot time
# Description:       Daemon for the smart home web dashboard
### END INIT INFO
#

#!/bin/sh

DIR=/usr/local/sbin/smarthome/web-dashboard
DAEMON=$DIR/dashboard.py
DAEMON_NAME=sh-web-dashboard
DAEMON_USER=root
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --chdir $DIR \
			--exec /bin/sh -- -c "$DAEMON >> /var/log/smarthome/web-dashboard.log 2>&1"
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping $DAEMON_NAME daemon"
    bashPID=$(cat $PIDFILE); [ -n "$bashPID" ] && pkill -P "$bashPID"
    #start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
    start|stop)
	do_${1}
	;;

    restart|reload|force-reload)
	do_stop
	do_start
	;;

    status)
	status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
	echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
	exit 1
	;;
esac
exit 0
